apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin
  labels:
    app: spring-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin
  template:
    metadata:
      labels:
        app: spring-admin
    spec:
      containers:
        - name: spring-admin
          image: alexandruvaratic/spring-admin:1.0.1
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_BOOT_ADMIN_CONTEXT_PATH
              value: /spring-admin