server:
  port: 8001

spring:
  application:
    name: cats-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  boot:
    admin:
      client:
        url: ${SPRING_ADMIN:http://localhost:8000/}
        instance:
          service-host-type: ip

management:
  endpoints:
    web:
      exposure:
        include: "*"